language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - 7.0

matrix:
    fast_finish: true
    allow_failures:
        - php: 7.0
        - php: hhvm

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.39.0.jar"
    - "java -jar selenium-server-standalone-2.39.0.jar > /tmp/selenium.log 2> /tmp/selenium.error &"
    - sh -c "echo 'extension = redis.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini"
    - /home/travis/.phpenv/versions/$(phpenv version-name)/bin/composer self-update
    - sh -c "sudo mkdir vendor"
    - sh -c "sudo mount -t tmpfs -o size=512M tmpfs vendor"

install:
    - composer install --prefer-source --no-interaction

before_script:
    - sh -c "sudo mkdir /tmp/Bamboo"
    - sh -c "sudo mount -t tmpfs -o size=512M tmpfs /tmp/Bamboo/"

services:
    - redis-server

script:
    - bin/behat -fprogress
    - bin/phpunit -c app

notifications:
    email: false

